name: Build and Generate Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.301' # replace with your .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --verbosity normal

    - name: Publish
      run: dotnet publish --configuration Release --no-build --output ./published

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Binary
        path: ./published/