name: Build and Generate Binary

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Unity
      uses: game-ci/unity-setup@v2
      with:
        unity-version: '2020.3.12f1' # replace with your Unity version

    - name: Build
      run: |
        /opt/Unity/Editor/Unity \
          -batchmode \
          -nographics \
          -silent-crashes \
          -logFile \
          -quit \
          -buildWindows64Player ./published/game.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: Binary
        path: ./published/